### Investigate Parquet file 

Look at parquet file to learn about the structure and content.

In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('/cmnfs/home/students/j.schlensok/oktoberfest/tutorials/out2/data/dlomix/refinement_dataset/processed_dataset.parquet')

In [3]:
df.columns

Index(['modified_sequence', 'precursor_charge_onehot',
       'collision_energy_aligned_normed', 'method_nbr', 'intensities_raw',
       'sequence', 'raw_file', 'scan_number'],
      dtype='object')

In [4]:
df

,modified_sequence,precursor_charge_onehot,collision_energy_aligned_normed,method_nbr,intensities_raw,sequence,raw_file,scan_number
0,AAAAAAYY,"[1, 0, 0, 0, 0, 0]",35,2,"[0.0, -1.0, -1.0, 0.0, -1.0, -1.0, 0.0, -1.0, ...",AAAAAAYY,GN20170722_SK_HLA_G0103_R1_01,35161
2,PTALHKQRL,"[0, 1, 0, 0, 0, 0]",35,2,"[1.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.0, 0.0, -1....",PTALHKQRL,GN20170722_SK_HLA_G0103_R1_01,21329
5,AAALALVAGVLSGAVLPL,"[0, 0, 0, 1, 0, 0]",35,2,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",AAALALVAGVLSGAVLPL,GN20170722_SK_HLA_G0103_R1_01,23664
7,AAALPAWL,"[0, 1, 0, 0, 0, 0]",35,2,"[1.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.0, 0.0, -1....",AAALPAWL,GN20170722_SK_HLA_G0103_R1_01,4619
8,RM[UNIMOD:35]PC[UNIMOD:4]HKPYL,"[0, 0, 1, 0, 0, 0]",35,2,"[1.0, 0.0, 0.0, 0.061912758193337705, 0.0, 0.0...",RMPCHKPYL,GN20170722_SK_HLA_G0103_R1_01,4619
...,...,...,...,...,...,...,...,...
22983,YYLEKREKKQNKW,"[0, 1, 0, 0, 0, 0]",35,2,"[0.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.0, 0.0, -1....",YYLEKREKKQNKW,GN20170722_SK_HLA_G0103_R2_02,37074
22985,YYPNPPLVL,"[0, 1, 0, 0, 0, 0]",35,2,"[1.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.38592193093...",YYPNPPLVL,GN20170722_SK_HLA_G0103_R2_02,30922
22986,YYPNPPLVL,"[0, 1, 0, 0, 0, 0]",35,2,"[1.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.40783274268...",YYPNPPLVL,GN20170722_SK_HLA_G0103_R2_02,30971
22990,YYSDEEDDQEEDNTSDDD,"[0, 1, 0, 0, 0, 0]",35,2,"[0.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.0, 0.0, -1....",YYSDEEDDQEEDNTSDDD,GN20170722_SK_HLA_G0103_R2_02,35543
22991,YYSSSEDE,"[0, 0, 1, 0, 0, 0]",35,2,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",YYSSSEDE,GN20170722_SK_HLA_G0103_R2_02,32043